server:
  port: 8080

openai:
  enabled: false                # set to true to use real APIs
  apiKey: ${OPENAI_API_KEY:}    # export OPENAI_API_KEY=sk-...
  baseUrl: https://api.openai.com/v1
  chatModel: gpt-4o-mini        # for text ? ingredients
  visionModel: gpt-4o-mini      # for image ? ingredients
